version: '3.1'

services:

  mongo: 
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: platzi
      MONGO_INITDB_ROOT_PASSWORD: platzi
  
  mongo-express: 
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: platzi
      ME_CONFIG_MONGODB_ADMINPASSWORD: platzi
      ME_CONFIG_MONGODB_URL: mongodb://platzi:platzi@mongo:27017/